spring.application.name=BibliothequeApp
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque
spring.datasource.username=postgres
spring.datasource.password=lemin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

# JWT Configuration
jwt.secret=ZGV2LWtleS1iaWJsaW90aGVxdWUtc3ByaW5nLXNlY3VyaXR5LWp3dC1zZWNyZXQtcGxlYXNlLWNoYW5nZS1pbi1wcm9kdWN0aW9u
jwt.expiration=86400000
